resolver 127.0.0.11 ipv6=off valid=15s;
resolver_timeout 5s;

server {
    listen 80;

    location / {
        set $upstream_back 'back:8080';
        proxy_pass http://$upstream_back;
    }

    location /docs/ {
        proxy_pass http://backend:8000/swagger;
    }
}